Iniciando cron job..
test 1 - 390420269
test 2 - 390420270
test 3 - 390420271
miau - 390420272
guau - 390420273
Finalizando cron job
Iniciando cron job..
Finalizando cron job
Iniciando cron job..
a ver a ver a ver - 390420274
Finalizando cron job
Iniciando cron job..
Finalizando cron job
Iniciando cron job..
wow - 390420275
funciona - 390420276
no - 390420277
me - 390420278
Finalizando cron job
Iniciando cron job..
Finalizando cron job
Iniciando cron job..
lo - 390420279
creooo - 390420280
Finalizando cron job
Iniciando cron job..
Finalizando cron job
Iniciando cron job..
Finalizando cron job
Iniciando cron job..
Finalizando cron job
Iniciando cron job..
Finalizando cron job
Iniciando cron job..
Finalizando cron job
Iniciando cron job..
Finalizando cron job
Iniciando cron job..
Finalizando cron job
Iniciando cron job..
Finalizando cron job
Iniciando cron job..
Finalizando cron job
Iniciando cron job..
Finalizando cron job
Iniciando cron job..
Finalizando cron job
Iniciando cron job..
Finalizando cron job
Iniciando cron job..
Finalizando cron job
Iniciando cron job..
Finalizando cron job
Iniciando cron job..
Finalizando cron job
Iniciando cron job..
Finalizando cron job
Iniciando cron job..
Finalizando cron job
Iniciando cron job..
Finalizando cron job
Iniciando cron job..
Finalizando cron job
Iniciando cron job..
Finalizando cron job
Iniciando cron job..
Finalizando cron job
Iniciando cron job..
Finalizando cron job
Iniciando cron job..
Finalizando cron job
Iniciando cron job..
Finalizando cron job
Iniciando cron job..
Finalizando cron job
Iniciando cron job..
Finalizando cron job
Iniciando cron job..
Finalizando cron job
System check identified some issues:

WARNINGS:
?: (urls.W002) Your URL pattern '/' [name='index'] has a route beginning with a '/'. Remove this slash as it is unnecessary. If this pattern is targeted in an include(), ensure the include() pattern has a trailing '/'.
perejil!!! - 390420281
A por uvas - 390420282
buuuuh - 390420283
última pruebita - 390420284
otra - 390420285
muh - 390420286
Traceback (most recent call last):
  File "/Users/diegocano/workspace/minordomo/manage.py", line 22, in <module>
    main()
  File "/Users/diegocano/workspace/minordomo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/diegocano/anaconda3/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/Users/diegocano/anaconda3/lib/python3.11/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/Users/diegocano/anaconda3/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/diegocano/anaconda3/lib/python3.11/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/Users/diegocano/anaconda3/lib/python3.11/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/diegocano/anaconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/diegocano/workspace/minordomo/minor_app/models.py", line 3, in <module>
    class Message(models.Model):
  File "/Users/diegocano/workspace/minordomo/minor_app/models.py", line 7, in Message
    read_status = models.BooleanField(default=false)
                                              ^^^^^
NameError: name 'false' is not defined. Did you mean: 'False'?
otrooo - 390420287
The crying of lot 49 - 390420288
hermenéutica - 390420289
solipsismo - 390420290
gamusino - 390420291
Traceback (most recent call last):
  File "/Users/diegocano/workspace/minordomo/manage.py", line 22, in <module>
    main()
  File "/Users/diegocano/workspace/minordomo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/diegocano/anaconda3/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/Users/diegocano/anaconda3/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/diegocano/anaconda3/lib/python3.11/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/diegocano/anaconda3/lib/python3.11/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/diegocano/anaconda3/lib/python3.11/site-packages/django_crontab/management/commands/crontab.py", line 29, in handle
    Crontab().run_job(options['jobhash'])
  File "/Users/diegocano/anaconda3/lib/python3.11/site-packages/django_crontab/crontab.py", line 142, in run_job
    module = import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/diegocano/anaconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/diegocano/workspace/minordomo/minor_app/cron.py", line 42, in <module>
    my_cron_job()
  File "/Users/diegocano/workspace/minordomo/minor_app/cron.py", line 37, in my_cron_job
    'chat_id': GROUP_ID,
               ^^^^^^^^
NameError: name 'GROUP_ID' is not defined
tela tela tela - 390420292
Voy a responder
Traceback (most recent call last):
  File "/Users/diegocano/workspace/minordomo/manage.py", line 22, in <module>
    main()
  File "/Users/diegocano/workspace/minordomo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/diegocano/anaconda3/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/Users/diegocano/anaconda3/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/diegocano/anaconda3/lib/python3.11/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/diegocano/anaconda3/lib/python3.11/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/diegocano/anaconda3/lib/python3.11/site-packages/django_crontab/management/commands/crontab.py", line 29, in handle
    Crontab().run_job(options['jobhash'])
  File "/Users/diegocano/anaconda3/lib/python3.11/site-packages/django_crontab/crontab.py", line 142, in run_job
    module = import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/diegocano/anaconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/diegocano/workspace/minordomo/minor_app/cron.py", line 43, in <module>
    my_cron_job()
  File "/Users/diegocano/workspace/minordomo/minor_app/cron.py", line 38, in my_cron_job
    'text': text
            ^^^^
NameError: name 'text' is not defined. Did you mean: 'next'?
Voy a responder
Respondí!
Voy a responder
Respondí!
buuuh - 390420294
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
nuevo mensaje 1 - 390420296
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Dieguini está bueno - 390420297
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Traceback (most recent call last):
  File "/Users/diegocano/workspace/minordomo/manage.py", line 22, in <module>
    main()
  File "/Users/diegocano/workspace/minordomo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/diegocano/anaconda3/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/Users/diegocano/anaconda3/lib/python3.11/site-packages/django/core/management/__init__.py", line 382, in execute
    settings.INSTALLED_APPS
  File "/Users/diegocano/anaconda3/lib/python3.11/site-packages/django/conf/__init__.py", line 89, in __getattr__
    self._setup(name)
  File "/Users/diegocano/anaconda3/lib/python3.11/site-packages/django/conf/__init__.py", line 76, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/diegocano/anaconda3/lib/python3.11/site-packages/django/conf/__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/diegocano/anaconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/diegocano/workspace/minordomo/minordomo/settings.py", line 16, in <module>
    load_dotenv()
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/Users/diegocano/workspace/minordomo/manage.py", line 22, in <module>
    main()
  File "/Users/diegocano/workspace/minordomo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/diegocano/anaconda3/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/Users/diegocano/anaconda3/lib/python3.11/site-packages/django/core/management/__init__.py", line 382, in execute
    settings.INSTALLED_APPS
  File "/Users/diegocano/anaconda3/lib/python3.11/site-packages/django/conf/__init__.py", line 89, in __getattr__
    self._setup(name)
  File "/Users/diegocano/anaconda3/lib/python3.11/site-packages/django/conf/__init__.py", line 76, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/diegocano/anaconda3/lib/python3.11/site-packages/django/conf/__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/diegocano/anaconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/diegocano/workspace/minordomo/minordomo/settings.py", line 16, in <module>
    load_dotenv()
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/Users/diegocano/workspace/minordomo/manage.py", line 22, in <module>
    main()
  File "/Users/diegocano/workspace/minordomo/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/diegocano/anaconda3/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/Users/diegocano/anaconda3/lib/python3.11/site-packages/django/core/management/__init__.py", line 382, in execute
    settings.INSTALLED_APPS
  File "/Users/diegocano/anaconda3/lib/python3.11/site-packages/django/conf/__init__.py", line 89, in __getattr__
    self._setup(name)
  File "/Users/diegocano/anaconda3/lib/python3.11/site-packages/django/conf/__init__.py", line 76, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/diegocano/anaconda3/lib/python3.11/site-packages/django/conf/__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/diegocano/anaconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/diegocano/workspace/minordomo/minordomo/settings.py", line 16, in <module>
    load_dotenv()
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Voy a responder
Respondí!
Voy a responder
Respondí!
pruebita - 390420298
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
Voy a responder
Respondí!
